### ISSUE TITLE
Works great, having issues packaging

### ISSUE THREAD

**Issue by BranigansLaw** [luferau/zoom-custom-ui-wpf#3]
I'm using this WPF application as a starting point for my own client. Everything works fantastically in Visual Studio 2019, but when I copy the compiled release as is, or in an MSI, any machine that I put the executable on gives me this error:

```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'zoom_sdk_dotnet_wrap.dll' or one
of its dependencies. The specified module could not be found.
```

Is there something special that needs to be done for distribution? Did you ever distribute this client to other platforms @luferau?

**Comment by luferau** [comment]
@BranigansLaw Does your bin\Release\ folder contain zoom_sdk_dotnet_wrap.dll (and Zoom SDK files)?
![zoom-release](https://user-images.githubusercontent.com/16937427/117030771-9ff66200-ad08-11eb-90a4-3a95e4addd43.png)

**Comment by luferau** [comment]
_Did you ever distribute this client to other platforms_

What do you mean by _other platforms_? It is only for windows.

**Comment by BranigansLaw** [comment]
> @BranigansLaw Does your bin\Release\ folder contain zoom_sdk_dotnet_wrap.dll (and Zoom SDK files)?

Definitely. My release directory looks just like that and works great on my machine, but when I copy it to another Windows machine, I get the error message `Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'zoom_sdk_dotnet_wrap.dll' or one of its dependencies. The specified module could not be found.`.

> What do you mean by other platforms? It is only for windows.

Sorry, by other platforms I just meant have you ever compiled on one Windows machine and then tried running that release in another Windows machine.

**Comment by luferau** [comment]
@BranigansLaw I checked on two PCs and did not see this error anywhere.

**Comment by BranigansLaw** [comment]
@luferau How did you copy the project over?

**Comment by luferau** [comment]
@BranigansLaw Ctrl+C/Ctrl+V (thru local network server shared folder) of all bin\Release\ folder.

**Comment by luferau** [comment]
@BranigansLaw Try to get SDK v.5.2.42037.1112. See repo README.md, paragraph 2.2. Get v.5.2.42037.1112 from https://github.com/zoom/zoom-c-sharp-wrapper/

**Comment by BranigansLaw** [comment]
> @BranigansLaw Ctrl+C/Ctrl+V (thru local network server shared folder) of all bin\Release\ folder.

I'm following the same procedure. Just had to check I wasn't missing something.

> @BranigansLaw Try to get SDK v.5.2.42037.1112. See repo README.md, paragraph 2.2. Get v.5.2.42037.1112 from https://github.com/zoom/zoom-c-sharp-wrapper/

Gave this a try, same result. This should be so basic. I have no idea why this isn't working.

**Comment by luferau** [comment]
@BranigansLaw Try to update this libraries https://www.microsoft.com/en-us/download/details.aspx?id=52685 Sometimes C++ apps/libs required this for running. 

Or use this updated link https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0

**Comment by BranigansLaw** [comment]
> Or use this updated link https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0

Thanks for the link. Installed this and even tried reinstalling all the C++ components for Visual Studio 2019 and had the same issue.

Another obvious questions but I'm running out of ideas on what I could be doing wrong. You're building this in Visual Studio 2019 Community?

**Comment by luferau** [comment]
> You're building this in Visual Studio 2019 Community?

No, I use Microsoft Visual Studio Enterprise 2019 Version 16.8.3

**Comment by BranigansLaw** [comment]
I have the most recent version, and I don't think MSBuild changes between Community and Enterprise. I might try reformatting my computer and see if that fixes it.

**Comment by BranigansLaw** [comment]
Got this figured out. The target machine needs to VC++ Redistributable installed on it.

For anyone having this issue, you can download the installer here: https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0
